### ISSUE TITLE
Windows版本lgs站点认证没有密钥选填项

### ISSUE THREAD

**Issue by 879611427** [QYG2297248353/IYUUPlus-Windows#1]
Windows版本更新到了8.2.55，列表中有了lgs，但是选项里没有passkey可填，安装的是1.1.5
![image](https://github.com/user-attachments/assets/86fbc467-cbac-4336-8140-1345fcb113ff)

**Comment by QYG2297248353** [comment]
> 感谢您的支持

1. 版本确认
+ 客户端 <= 1.1.4
![image](https://github.com/user-attachments/assets/d2fba310-8bf0-460e-9603-cad2132c50e3)
请安装 git 后，重启客户端，通过首页更新内核
![image](https://github.com/user-attachments/assets/63275578-1617-48ee-92b4-1ca945714e0b)
+ 客户端 为 1.1.5 LTS
请在首页，仪表盘进行更新内核至 8.2.55

2. 站点同步
![image](https://github.com/user-attachments/assets/5a8394f8-9efb-4aea-af01-42940b736972)

通过 获取最新站点信息 按钮更新站点

3. 重启客户端，查看站点配置
![image](https://github.com/user-attachments/assets/c6643561-e1bc-4941-ada6-37f7c046c98d)

**Comment by 879611427** [comment]
可以了，没有点击获取最新配置
